### ISSUE TITLE
Python3 compatibility

### ISSUE THREAD

**Issue by Luca-Pozzi** [neka-nat/ros_np_multiarray#1]
Hi,
first of all, thanks for this super-useful package! 

I would like to highlight some compatibility issue with Python3 and how I managed to solve them.

# Import statement
The import statement shown in the README causes an `AttributeError`, specifically:

> `AttributeError: module 'ros_np_multiarray' has no attribute 'to_multiarray_f32'`

Instead, one should use 

> `from ros_np_multiarray import ros_np_multiarray as rnm` 

and everything works fine. 

# Conversion to NumPy
When running one of the `to_numpy`, a `TypeError` occurs, specifically:

> `TypeError: expected sequence object with len >= 0 or a single integer`

The issue can be solved by modifying the first line of the `_multiarray_to_numpy` function to convert `dims` to a *tuple*, i.e.

> `dims = tuple(map(lambda x: x.size, multiarray.layout.dim))`

* * *

As the mentioned changes seem to work in Python2.7 as well, it could be useful to update the code in order to achieve Python3 compatibility.

System's info:
- Ubuntu 18.04-LTS
- ROS Melodic

**Comment by Luca-Pozzi** [comment]
The suggested changes have been merged with PR #3
